/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import HeroPage from './HeroPage'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, Html, useCursor } from '@react-three/drei'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

export function Model(props) {
  const { nodes, materials } = useGLTF('./model/kamar2.glb')
  const navigate = useNavigate();

  const { camera } = useThree();
  const [showHtml, setShowHtml] = useState(false)
  const [showItem, setshowItem] = useState(false)
  const targetPosition = new THREE.Vector3(-0.5490231344449, 2.974757394954851,  -1.80)
  const targetPosition2 = new THREE.Vector3(-1.9480259020108315, 2.7969450450499505, -0.029262465466163064)
  const targetPosition3 = new THREE.Vector3(-0.55, 2.97, -1.1)
  const [hovered, setHovered] = useState(false)
  useCursor(hovered)

  const handleClick = () => {
    window.open('https://github.com/keshmaSalgado', '_blank')
  }

  const handleClickLinkdln = () => {
    window.open('https://www.linkedin.com/in/keshma-salgado-6541932a8/', '_blank')
  }


  useFrame(() => {
    if (camera.position.distanceTo(targetPosition) < 0.1 ||camera.position.distanceTo(targetPosition3) < 0.1) {
      setShowHtml(true)
    } else {
      setShowHtml(false)
    }
    if (camera.position.distanceTo(targetPosition2) < 0.1) {
      setshowItem(true)
    } else {
      setshowItem(false)
    }

  })
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.711, 0]} scale={2.64}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.042']}
        />
      </group>
      <pointLight
        intensity={100}
        decay={2}
        position={[3.938, 7.835, -1.691]}
        rotation={[-1.839, 0.602, 1.932]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.895}
        position={[12.67, 8.978, 11.774]}
        rotation={[-0.445, 0.731, 0.308]}
      />
      <group
        position={[-2.026, 2.317, -0.993]}
        rotation={[0, 1.571, 0]}
        scale={[1.653, 0.111, 0.569]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.006']}
        />
      </group>
      <group
        position={[-2.522, 2.735, 1.79]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.343, 0.343, 0.425]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_3.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_4.geometry}
          material={materials['Material.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_5.geometry}
          material={materials['Material.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_6.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_7.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_8.geometry}
          material={materials['Material.017']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_9.geometry}
          material={materials['Material.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_10.geometry}
          material={materials['Material.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_11.geometry}
          material={materials['Material.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_12.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_13.geometry}
          material={materials['Material.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_14.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_15.geometry}
          material={materials['Material.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_16.geometry}
          material={materials['Material.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_17.geometry}
          material={materials['Material.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_18.geometry}
          material={materials['Material.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_19.geometry}
          material={materials['Material.028']}
        />
      </group>
      <group
        position={[-1.833, 2.441, -0.748]}
        rotation={[0, 1.184, 0]}
        scale={[0.474, 0.015, 0.24]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109.geometry}
          material={materials['Material.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_1.geometry}
          material={materials['Material.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_2.geometry}
          material={materials['Material.037']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_3.geometry}
          material={materials['Material.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_4.geometry}
          material={materials['Material.039']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109_5.geometry}
          material={materials['Material.034']}
        />
      </group>
      <group
        position={[0.074, 2.78, -0.689]}
        rotation={[-0.212, -0.558, -0.113]}
        scale={[0.419, 0.963, 0.103]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube215.geometry}
          material={materials['Material.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube215_1.geometry}
          material={materials['Material.041']}
        />
      </group>
      <directionalLight
        intensity={0.1}
        decay={2}
        position={[0.434, 16.314, -0.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.385}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitor1image.geometry}
        material={materials['Material.043']}
        position={[-2.04, 3.015, -1.191]}
        rotation={[1.517, -0.044, -1.389]}
        scale={[0.372, 1.002, 0.608]}
      />
      <group
        position={[-2.051, 3.012, -1.196]}
        rotation={[0.147, 0.971, -0.121]}
        scale={[0.769, 0.383, 0.022]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials['Material.008']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo'].geometry}
        material={materials['react-logo']}
        position={[-2.368, 3.222, -0.664]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo001'].geometry}
        material={materials['react-logo.001']}
        position={[-2.371, 3.076, -0.678]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo002'].geometry}
        material={materials['react-logo.003']}
        position={[-2.371, 2.9, -0.678]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo003'].geometry}
        material={materials['react-logo.004']}
        position={[-2.262, 3.222, -0.832]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo004'].geometry}
        material={materials['react-logo.005']}
        position={[-2.264, 3.076, -0.846]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo005'].geometry}
        material={materials['react-logo.006']}
        position={[-2.273, 2.9, -0.846]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo006'].geometry}
        material={materials['react-logo.008']}
        position={[-2.164, 3.208, -0.974]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo007'].geometry}
        material={materials['react-logo.007']}
        position={[-2.166, 3.061, -0.987]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['react-logo008'].geometry}
        material={materials['react-logo.009']}
        position={[-2.175, 2.903, -1.002]}
        rotation={[1.602, -0.039, -0.978]}
        scale={0.101}
      />
      <group position={[-1.973, 2.427, -0.042]} rotation={[-1.571, -0.001, 1.806]} scale={1.239}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.IPHONE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials['iphone-x-screenshot']}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_2.geometry}
          material={materials.glass}
        /> */}
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.iphone_screen}
        position={[-1.972, 2.438, -0.041]}
        rotation={[0, 0.235, 0]}
        scale={[0.199, 0.538, 0.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.github.geometry}
        material={materials.github}
        visible={showItem && true}
        position={[-2.034, 2.439, -0.025]}
        rotation={[-Math.PI, 1.325, -Math.PI]}
        scale={[0.034, 1, 0.018]}
        onClick={handleClick}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.instargram.geometry}
        material={materials.instargram}
        visible={showItem && true}
        position={[-1.994, 2.439, -0.036]}
        rotation={[-Math.PI, 1.334, -Math.PI]}
        scale={[0.034, 1, 0.018]}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
        onClick={() => navigate("/gmail")}

      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.linkdln.geometry}
        visible={showItem && true}
        material={materials.linkdln}
        position={[-1.953, 2.439, -0.046]}
        rotation={[-Math.PI, 1.326, -Math.PI]}
        scale={[0.034, 1, 0.018]}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
        onClick={handleClickLinkdln}

      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gmail.geometry}
        visible={showItem && true}
        material={materials.gmail}
        position={[-1.913, 2.439, -0.057]}
        rotation={[-Math.PI, 1.326, -Math.PI]}
        scale={[0.034, 1, 0.018]}
        onClick={() => navigate("/gmail")}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
      <group position={[-0.624, 2.428, -2.185]} scale={0.073}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials['aluminium.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['trackpad.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keyboard001.geometry}
        material={materials['keys.002']}
        position={[-0.494, 2.435, -2.181]}
        scale={0.073}
      />
      <group position={[-0.624, 2.432, -2.402]} rotation={[0.014, 0, 0]} scale={0.073}>
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials['aluminium.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials['matte.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials['screen.003']}
          >
            {showHtml && (
              <Html
                className="content"
                rotation-x={-Math.PI / 2}
                position={[-0.02, 0.039, -0.1]}
                transform
                occlude
              >
                <div className="wrapper" onPointerDown={(e) => e.stopPropagation()}>
                  <HeroPage />
                </div>
              </Html>
            )}
          </mesh>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.touchbar.geometry}
        material={materials['touchbar.002']}
        position={[-0.624, 2.433, -2.345]}
        scale={0.073}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.010']}
        position={[-2.495, 5.236, 2.104]}
        rotation={[1.162, 0.074, -1.572]}
        scale={0.822}
      />
    </group>
  )
}

useGLTF.preload('./model/kamar2.glb')


